server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:3001/csis231_bookstore
    username: postgres
    password: elise
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
  sql:
    init:
      mode: always
